### ISSUE TITLE
Replacing associations support

### ISSUE THREAD

**Issue by kennyadsl** [jhawthorn/discard#26]
Hey @jhawthorn !

We've an [issue on Solidus](https://github.com/solidusio/solidus/issues/2744) that made me notice that when an association collection is replaced with `=` ([CollectionProxy#replace](https://apidock.com/rails/ActiveRecord/Associations/CollectionProxy/replace)) record discarding is not performed. 

I have a failing test in my discard fork with this commit: https://github.com/kennyadsl/discard/commit/b7877f0cda188ea517edd240d97e31ebb7fbb0e3

Do you think it's something that should be handled here or if discard is used it's always better to manually call `discard_all` before adding new items to a collection?

**Comment by blocknotes** [comment]
Hi @kennyadsl.
IMO this case should be handled in the app, not in the *discard* gem, because it does not override AR *delete* / *destroy* methods.

An option can be:
`has_many :posts, after_remove: ->(author, post) { post.discard }`

Test updated here:
https://github.com/blocknotes/discard/commit/409b1ee94feae7a06961ccadab05aceb6196b200

**Comment by jarednorman** [comment]
Hey @kennyadsl, I believe this was recently discussed on #42. If I understand correctly, fixing your failing test would require overriding default ActiveRecord behaviour. Part of the goal of discard is to avoid ever overriding any ActiveRecord behaviour, so users of the gem are expected to manually call `discard_all` in advance if they want to do this.
