### ISSUE TITLE
Discarding should skip validations (maybe)

### ISSUE THREAD

**Issue by slaith** [jhawthorn/discard#35]
A lot of times, validations to the model are added in retrospect. The usual action thereafter would be to discard the instances that are not validated. This doesn't work as expected since the lack of validation would prevent the instance from being shelved.
Undiscard should ideally not work when validations fail, but I am not sure discard should follow the validations rule.

**Comment by Sudrien** [comment]
Ran into this - as there are, on occasion, reasons to save without validation, there would be reasons to discard as well, even with out the old data scenario.

Perhaps a `discard(:validate => false)`

which would use `update_column` instead of  `update_attribute`?

**Comment by jamesst20** [comment]
I agree on this. In our application we have a scenario where some fields must be filled by a candidate which receive an invitation link to fill the form. 

In this case, validations fail because the candidate hasn't filled the form yet and we can't discard the model.

**Comment by jamesst20** [comment]
Validations are already skipped since this change https://github.com/jhawthorn/discard/commit/dfdd984b37bf3d646b276d68e47f7f998c6aaad9#diff-0a62a055b1aeb5c4b72b9318cebd32f2

It seems like the gem release is outdated.
Easy workaround, use this instead inside Gemfile

gem "discard", git: "https://github.com/jhawthorn/discard.git"

**Comment by jonkarna** [comment]
Is there a reason why there isn't a new gem version?

**Comment by jarednorman** [comment]
Stale issue, we've cut some releases since then. 🤘🏻

**Comment by zacheryph** [comment]
Just wanted to note as a coworker pointed out today... The above mentioned change also manages to remove validations when UNdiscarding a record. It seems weird to not want to run validations when we are for all intents and purposes, [re] creating a record?

**Comment by rkofman** [comment]
Concur that skipping validations by default is.. surprising -- for both `discard` and (especially) `undiscard`. I expect each method to simply be a shorthand for setting the `discarded_at` value and then calling `save`.

I would propose a better solve to this issue would have been to simply accept a `skip_validations` parameter; much like one would do with `save`. However, I understand this issue is from 7 years ago; and this is a rather small project -- so I don't expect an update, and would only be pleasantly surprised if this spurred one :)

But if readers stumble on this; a potential fix may look like:
```
def discard(**save_options)
  return false if discarded?
  
  run_callbacks(:discard) do
    self[self.class.discard_column] = Time.current
    save(**save_options)
  end
end

def undiscard(**save_options)
  return false unless discarded?
  
  run_callbacks(:undiscard) do
    self[self.class.discard_column] = nil
    save(**save_options)
  end
end
```
