### ISSUE TITLE
Discard callbacks don't work with observers

### ISSUE THREAD

**Issue by pelargir** [jhawthorn/discard#67]
**Describe the bug**
Calling `#discard` on an ActiveRecord object does not trigger any `before_discard` or `after_discard` callbacks defined in Rails observers.

**To Reproduce**
1. Install the `rails-observers` gem
2. Create an observer class for your ActiveRecord object
3. Define a `before_discard` or `after_discard` callback in the observer
4. Discard your ActiveRecord object
5. The callback will not fire

**Expected behavior**
Discard callbacks should be usable in Rails observers. It would be relatively straightforward to hook into `ActiveRecord::Observer` and add the callbacks when `rails-observers` is detected. I'd be happy to submit a PR if this is something you would actually consider merging.

**Additional context**
Rails 5.2
Ruby 2.5.7
rails-observers 0.1.5
discard 1.1.0

**Comment by jarednorman** [comment]
Hey, thanks for opening this issue. I took a quick look at the `rails-observers` gem, and if I understand it correctly, it looks the change required for these gems to work together needs to modify/monkey-patch the Active Record observer to hook into the callbacks discard provides. I don't imagine that will require much code at all.

That said, I consider support for `rails-observers` to be a feature that not all users of this gem may need. As per the explanation in the [contributing guidelines](https://github.com/jhawthorn/discard#contributing) I don't think this belongs in the core of discard. If you were to implement this modification of `rails-observers` in a separate gem, I'd love to link to it in the README, so that those who need/want this functionality can find it easily.

**Comment by pelargir** [comment]
@jarednorman yes, it's fairly straightforward. Here's what I came up with: https://github.com/pelargir/discard-rails-observers
https://rubygems.org/gems/discard-rails-observers

**Comment by jarednorman** [comment]
Very cool, thanks for putting that together. I'm sure others will find it useful. I'll add a link to your gem in the README.
