### ISSUE TITLE
discarding on nested_attributes

### ISSUE THREAD

**Issue by hobbypunk90** [jhawthorn/discard#7]
Hello,

i have a little problem with `accepts_nested_attributes_for`, is there a standard workaround for discarding such "children" instead of destroying them?

Greets
Marcel

**Comment by jhawthorn** [comment]
Hi Marcel. I haven't run into this yet, but we should find a solution to put in the README.

Records are normally deleted through `accepts_nested_attributes_for` using a `_destroy` key, right? Is it possible to just set `discarded_at` with the current time instead of `_destroy`?

**Comment by hobbypunk90** [comment]
hi,
yes, records are destroyed with a `_destroy` key.
That's my problem, there are a few ways to set the `discarded_at`, we can walk through the params on server side and check the the `_destroy` key, but thats not nice, for nested `accepts_nested_attributes_for`
the simplest/possible best way looks like to set it on client side i think.

**Comment by hobbypunk90** [comment]
i have a working solution now:
for the client side i have this:
```coffee
$('.simple_form').on 'cocoon:after-remove', (e, elem) ->
    if $(elem.context).siblings "[id$=discarded_at]"
      $(elem.context).siblings("[id$=_destroy]").val(false)
      $(elem.context).siblings("[id$=discarded_at]").val(new Date(Date.now()))
```
and in my views a have to add a hidden field for `discarded_at`
```slim
= f.hidden_field :discarded_at
= link_to_remove_association f
```

**Comment by njcameron** [comment]
This worked for me. Don't forget to add discarded_at to your strong params.

**Comment by daveharris** [comment]
I know that this is really old but I came across it when searching for whether there was a built-in way to do this. I turns out that there doesn't need to be any special sauce at all, it just can be done from the view.

```erb
<%= ff.check_box :discarded_at, {}, Time.current, nil %>
<%= ff.label :discarded_at %>
```

No javascript or anything else!

While the discarded time is slightly incorrect given it's a page render time, not at form submission time - in my use case it's sufficient for the task. If you needed accurate timing you would be able catch it using `[ActiveModel::Dirty](https://api.rubyonrails.org/classes/ActiveModel/Dirty.html)` in the controller after `assign_attributes(params)` with `model.discarded_at_changed?(from: nil)`, and if true updating the time to `Time.current`.

Also as @njcameron said, you still need to allow through Strong Params too.
